eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.25.64:8761/eureka/
      
server:
  port: 8768
  
feign: 
  hystrix:
    enabled: true
  
spring:
  application:
    name: eshop-one-service